// <auto-generated />
namespace Lures.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class phonetostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phonetostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201707020657442_phone-to-string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
